// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID          string
	Subject     string
	Payload     []byte
	Headers     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
}

type Payment struct {
	ID            string
	OrderID       string
	CustomerID    string
	CurrencyCode  string
	AmountMinor   int64
	Status        string
	FailureReason string
	ProviderRef   string
	CreatedAt     time.Time
}
