// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT id, order_id, customer_id, currency_code, amount_minor, status, failure_reason, provider_ref, created_at
FROM payments
WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrder(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.CurrencyCode,
		&i.AmountMinor,
		&i.Status,
		&i.FailureReason,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (id, order_id, customer_id, currency_code, amount_minor, status, failure_reason, provider_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, customer_id, currency_code, amount_minor, status, failure_reason, provider_ref, created_at
`

type InsertPaymentParams struct {
	ID            string
	OrderID       string
	CustomerID    string
	CurrencyCode  string
	AmountMinor   int64
	Status        string
	FailureReason string
	ProviderRef   string
}

// Returns no row when the order already has a payment; the caller then reads the existing one.
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.CurrencyCode,
		arg.AmountMinor,
		arg.Status,
		arg.FailureReason,
		arg.ProviderRef,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.CurrencyCode,
		&i.AmountMinor,
		&i.Status,
		&i.FailureReason,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}
