// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inbox struct {
	Consumer    string
	MessageID   string
	ProcessedAt pgtype.Timestamptz
}

type Outbox struct {
	ID          string
	Subject     string
	Payload     []byte
	Headers     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Reservation struct {
	OrderID    string
	Status     string
	CreatedAt  pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
}

type ReservationLine struct {
	OrderID  string
	Sku      string
	Quantity int32
}

type StockItem struct {
	Sku            string
	Name           string
	CurrencyCode   string
	UnitPriceMinor int64
	OnHand         int32
	Reserved       int32
}
