// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (order_id, status) VALUES ($1, $2)
`

type CreateReservationParams struct {
	OrderID string
	Status  string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation, arg.OrderID, arg.Status)
	return err
}

const createReservationLine = `-- name: CreateReservationLine :exec
INSERT INTO reservation_lines (order_id, sku, quantity) VALUES ($1, $2, $3)
`

type CreateReservationLineParams struct {
	OrderID  string
	Sku      string
	Quantity int32
}

func (q *Queries) CreateReservationLine(ctx context.Context, arg CreateReservationLineParams) error {
	_, err := q.db.Exec(ctx, createReservationLine, arg.OrderID, arg.Sku, arg.Quantity)
	return err
}

const getItem = `-- name: GetItem :one
SELECT sku, name, currency_code, unit_price_minor, on_hand, reserved
FROM stock_items
WHERE sku = $1
`

func (q *Queries) GetItem(ctx context.Context, sku string) (StockItem, error) {
	row := q.db.QueryRow(ctx, getItem, sku)
	var i StockItem
	err := row.Scan(
		&i.Sku,
		&i.Name,
		&i.CurrencyCode,
		&i.UnitPriceMinor,
		&i.OnHand,
		&i.Reserved,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT order_id, status FROM reservations WHERE order_id = $1
`

type GetReservationRow struct {
	OrderID string
	Status  string
}

func (q *Queries) GetReservation(ctx context.Context, orderID string) (GetReservationRow, error) {
	row := q.db.QueryRow(ctx, getReservation, orderID)
	var i GetReservationRow
	err := row.Scan(&i.OrderID, &i.Status)
	return i, err
}

const getReservationLines = `-- name: GetReservationLines :many
SELECT sku, quantity FROM reservation_lines WHERE order_id = $1 ORDER BY sku
`

type GetReservationLinesRow struct {
	Sku      string
	Quantity int32
}

func (q *Queries) GetReservationLines(ctx context.Context, orderID string) ([]GetReservationLinesRow, error) {
	rows, err := q.db.Query(ctx, getReservationLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservationLinesRow
	for rows.Next() {
		var i GetReservationLinesRow
		if err := rows.Scan(&i.Sku, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT sku, name, currency_code, unit_price_minor, on_hand, reserved
FROM stock_items
WHERE sku > $1
ORDER BY sku
LIMIT $2
`

type ListItemsParams struct {
	Sku   string
	Limit int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]StockItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Sku, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockItem
	for rows.Next() {
		var i StockItem
		if err := rows.Scan(
			&i.Sku,
			&i.Name,
			&i.CurrencyCode,
			&i.UnitPriceMinor,
			&i.OnHand,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItems = `-- name: LockItems :many
SELECT sku, name, currency_code, unit_price_minor, on_hand, reserved
FROM stock_items
WHERE sku = ANY($1::text[])
ORDER BY sku
FOR UPDATE
`

// Rows are locked in SKU order so concurrent reservations cannot deadlock.
func (q *Queries) LockItems(ctx context.Context, dollar_1 []string) ([]StockItem, error) {
	rows, err := q.db.Query(ctx, lockItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockItem
	for rows.Next() {
		var i StockItem
		if err := rows.Scan(
			&i.Sku,
			&i.Name,
			&i.CurrencyCode,
			&i.UnitPriceMinor,
			&i.OnHand,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReservationStatus = `-- name: SetReservationStatus :exec
UPDATE reservations
SET status = $2,
    released_at = CASE WHEN $2 = 'released' THEN now() ELSE released_at END
WHERE order_id = $1
`

type SetReservationStatusParams struct {
	OrderID string
	Status  string
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) error {
	_, err := q.db.Exec(ctx, setReservationStatus, arg.OrderID, arg.Status)
	return err
}

const setReserved = `-- name: SetReserved :exec
UPDATE stock_items SET reserved = $2 WHERE sku = $1
`

type SetReservedParams struct {
	Sku      string
	Reserved int32
}

func (q *Queries) SetReserved(ctx context.Context, arg SetReservedParams) error {
	_, err := q.db.Exec(ctx, setReserved, arg.Sku, arg.Reserved)
	return err
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO stock_items (sku, name, currency_code, unit_price_minor, on_hand)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sku) DO NOTHING
`

type UpsertItemParams struct {
	Sku            string
	Name           string
	CurrencyCode   string
	UnitPriceMinor int64
	OnHand         int32
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.Sku,
		arg.Name,
		arg.CurrencyCode,
		arg.UnitPriceMinor,
		arg.OnHand,
	)
	return err
}
