// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Notification struct {
	ID            string
	OrderID       string
	CustomerID    string
	Kind          string
	Channel       string
	Recipient     string
	Subject       string
	Body          string
	Status        string
	FailureReason string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
