// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const getNotificationByKey = `-- name: GetNotificationByKey :one
SELECT id, order_id, customer_id, kind, channel, recipient, subject, body, status, failure_reason, created_at, updated_at
FROM notifications
WHERE order_id = $1 AND kind = $2 AND channel = $3
`

type GetNotificationByKeyParams struct {
	OrderID string
	Kind    string
	Channel string
}

func (q *Queries) GetNotificationByKey(ctx context.Context, arg GetNotificationByKeyParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByKey, arg.OrderID, arg.Kind, arg.Channel)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.Kind,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (id, order_id, customer_id, kind, channel, recipient, subject, body, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (order_id, kind, channel) DO NOTHING
RETURNING id, order_id, customer_id, kind, channel, recipient, subject, body, status, failure_reason, created_at, updated_at
`

type InsertNotificationParams struct {
	ID         string
	OrderID    string
	CustomerID string
	Kind       string
	Channel    string
	Recipient  string
	Subject    string
	Body       string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Returns no row when this (order, kind, channel) was already recorded; the caller then reads the existing one.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.Kind,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.Kind,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationsAfter = `-- name: ListNotificationsAfter :many
SELECT id, order_id, customer_id, kind, channel, recipient, subject, body, status, failure_reason, created_at, updated_at
FROM notifications
WHERE ($1::text = '' OR order_id = $1::text)
  AND ($2::text = '' OR customer_id = $2::text)
  AND (created_at, id) < ($3::timestamptz, $4::text)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListNotificationsAfterParams struct {
	OrderID        string
	CustomerID     string
	AfterCreatedAt time.Time
	AfterID        string
	PageLimit      int32
}

func (q *Queries) ListNotificationsAfter(ctx context.Context, arg ListNotificationsAfterParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsAfter,
		arg.OrderID,
		arg.CustomerID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsFirstPage = `-- name: ListNotificationsFirstPage :many
SELECT id, order_id, customer_id, kind, channel, recipient, subject, body, status, failure_reason, created_at, updated_at
FROM notifications
WHERE ($1::text = '' OR order_id = $1::text)
  AND ($2::text = '' OR customer_id = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotificationsFirstPageParams struct {
	OrderID    string
	CustomerID string
	PageLimit  int32
}

func (q *Queries) ListNotificationsFirstPage(ctx context.Context, arg ListNotificationsFirstPageParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsFirstPage, arg.OrderID, arg.CustomerID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.Kind,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications SET status = 'failed', failure_reason = $2, updated_at = $3 WHERE id = $1 AND status = 'pending'
`

type MarkNotificationFailedParams struct {
	ID            string
	FailureReason string
	UpdatedAt     time.Time
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.FailureReason, arg.UpdatedAt)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET status = 'sent', updated_at = $2 WHERE id = $1 AND status = 'pending'
`

type MarkNotificationSentParams struct {
	ID        string
	UpdatedAt time.Time
}

// Only a pending notification can become sent; final states never change.
func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.ID, arg.UpdatedAt)
	return err
}
