// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Inbox struct {
	Consumer    string
	MessageID   string
	ProcessedAt time.Time
}

type Order struct {
	ID             string
	CustomerID     string
	IdempotencyKey string
	CurrencyCode   string
	TotalMinor     int64
	Status         string
	CancelReason   string
	RefundRequired bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type OrderItem struct {
	OrderID        string
	Sku            string
	Quantity       int32
	UnitPriceMinor int64
}

type Outbox struct {
	ID          string
	Subject     string
	Payload     []byte
	Headers     []byte
	CreatedAt   time.Time
	PublishedAt pgtype.Timestamptz
}
