// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const getItemsForOrders = `-- name: GetItemsForOrders :many
SELECT order_id, sku, quantity, unit_price_minor
FROM order_items
WHERE order_id = ANY($1::text[])
ORDER BY order_id, sku
`

func (q *Queries) GetItemsForOrders(ctx context.Context, dollar_1 []string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getItemsForOrders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.Sku,
			&i.Quantity,
			&i.UnitPriceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.CurrencyCode,
		&i.TotalMinor,
		&i.Status,
		&i.CancelReason,
		&i.RefundRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByKey = `-- name: GetOrderByKey :one
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders WHERE customer_id = $1 AND idempotency_key = $2
`

type GetOrderByKeyParams struct {
	CustomerID     string
	IdempotencyKey string
}

func (q *Queries) GetOrderByKey(ctx context.Context, arg GetOrderByKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByKey, arg.CustomerID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.CurrencyCode,
		&i.TotalMinor,
		&i.Status,
		&i.CancelReason,
		&i.RefundRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.CurrencyCode,
		&i.TotalMinor,
		&i.Status,
		&i.CancelReason,
		&i.RefundRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (customer_id, idempotency_key) DO NOTHING
RETURNING id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
`

type InsertOrderParams struct {
	ID             string
	CustomerID     string
	IdempotencyKey string
	CurrencyCode   string
	TotalMinor     int64
	Status         string
	CancelReason   string
	RefundRequired bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Returns no row when the customer already used this idempotency key; the caller then reads the existing order.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.CustomerID,
		arg.IdempotencyKey,
		arg.CurrencyCode,
		arg.TotalMinor,
		arg.Status,
		arg.CancelReason,
		arg.RefundRequired,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.CurrencyCode,
		&i.TotalMinor,
		&i.Status,
		&i.CancelReason,
		&i.RefundRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (order_id, sku, quantity, unit_price_minor) VALUES ($1, $2, $3, $4)
`

type InsertOrderItemParams struct {
	OrderID        string
	Sku            string
	Quantity       int32
	UnitPriceMinor int64
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.Sku,
		arg.Quantity,
		arg.UnitPriceMinor,
	)
	return err
}

const listOrdersAfter = `-- name: ListOrdersAfter :many
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders
WHERE ($1::text = '' OR customer_id = $1::text)
  AND (created_at, id) < ($2::timestamptz, $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListOrdersAfterParams struct {
	CustomerID     string
	AfterCreatedAt time.Time
	AfterID        string
	PageLimit      int32
}

func (q *Queries) ListOrdersAfter(ctx context.Context, arg ListOrdersAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersAfter,
		arg.CustomerID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IdempotencyKey,
			&i.CurrencyCode,
			&i.TotalMinor,
			&i.Status,
			&i.CancelReason,
			&i.RefundRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersFirstPage = `-- name: ListOrdersFirstPage :many
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders
WHERE ($1::text = '' OR customer_id = $1::text)
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersFirstPageParams struct {
	CustomerID string
	PageLimit  int32
}

func (q *Queries) ListOrdersFirstPage(ctx context.Context, arg ListOrdersFirstPageParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersFirstPage, arg.CustomerID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IdempotencyKey,
			&i.CurrencyCode,
			&i.TotalMinor,
			&i.Status,
			&i.CancelReason,
			&i.RefundRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStaleOrders = `-- name: LockStaleOrders :many
SELECT id, customer_id, idempotency_key, currency_code, total_minor, status, cancel_reason, refund_required, created_at, updated_at
FROM orders
WHERE status IN ('pending', 'stock_reserved') AND updated_at < $1
ORDER BY updated_at, id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type LockStaleOrdersParams struct {
	UpdatedAt time.Time
	Limit     int32
}

// Unfinished orders nobody has updated since the cutoff. SKIP LOCKED lets several sweepers run side by side.
func (q *Queries) LockStaleOrders(ctx context.Context, arg LockStaleOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, lockStaleOrders, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IdempotencyKey,
			&i.CurrencyCode,
			&i.TotalMinor,
			&i.Status,
			&i.CancelReason,
			&i.RefundRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET status = $2, cancel_reason = $3, refund_required = $4, updated_at = $5
WHERE id = $1
`

type UpdateOrderParams struct {
	ID             string
	Status         string
	CancelReason   string
	RefundRequired bool
	UpdatedAt      time.Time
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.Exec(ctx, updateOrder,
		arg.ID,
		arg.Status,
		arg.CancelReason,
		arg.RefundRequired,
		arg.UpdatedAt,
	)
	return err
}
